version: '3'

services:
    db:
        container_name: csh_db
        image: postgres:10
        ports:
            - 5444:5432
        environment:
            - POSTGRES_DB=${PGDATABASE}
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${PGPASSWORD}
    webapp:
        container_name: webapp
        build: ./webapp
        depends_on:
            - db
        volumes:
            - '.:/csh'
        ports:
            - 5000:5000
        environment:
            # Flask
            - SECRET_KEY
            - DEBUG
            - SECURITY_PASSWORD_SALT
            # S3 Configuration
            - RAW_UPLOADS_PATH=s3://dsapp-criminal-justice/csh/matcher/{jurisdiction}/{event_type}/uploaded/{date}/{upload_id}
            - MERGED_UPLOADS_PATH=s3://dsapp-criminal-justice/csh/matcher/{jurisdiction}/{event_type}/merged
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            # Database connection
            - PGHOST=csh_db
            - PGPORT=5432
            - PGUSER
            - PGDATABASE
            - PGPASSWORD
            # Matcher connection
            - MATCHER_LOCATION=matcher
            - MATCHER_PORT=5000

    matcher:
        container_name: matcher
        build: ./matcher
        volumes:
            - '.:/csh' # HOST:CONTAINER
        ports:
            - 5001:5000 # HOST:CONTAINER
        environment:
            # File storage configuration
            - S3_BUCKET=dsapp-criminal-justice
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            # Matcher distance calculation configuration
            - INDEXER=identity
            - KEYS=['first_name', 'middle_name', 'last_name', 'dob', 'ssn', 'dmv_number', 'dmv_state', 'race', 'ethnicity', 'sex']
            - CONTRASTER=exact
            # Matcher clustering configuration
            - EPS=0.5
            - MIN_SAMPLES=1
            - ALGORITHM=auto
            - LEAF_SIZE=30
            - N_JOBS=1
            # Database connection configuration
            - PGHOST=csh_db
            - PGPORT=5432
            - PGUSER
            - PGDATABASE
            - PGPASSWORD

    matcher_worker:
        image: csh_matcher
        container_name: matcher_worker
        command: python manage.py
        volumes:
            - '.:/csh'
        depends_on:
            - redis
            - matcher
        environment:
            # File storage configuration
            - S3_BUCKET=dsapp-criminal-justice
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            # Matcher distance calculation configuration
            - INDEXER=identity
            - KEYS=['first_name', 'middle_name', 'last_name', 'dob', 'ssn', 'dmv_number', 'dmv_state', 'race', 'ethnicity', 'sex']
            - CONTRASTER=exact
            # Matcher clustering configuration
            - EPS=0.5
            - MIN_SAMPLES=1
            - ALGORITHM=auto
            - LEAF_SIZE=30
            - N_JOBS=1
            # Database connection configuration
            - PGHOST=csh_db
            - PGPORT=5432
            - PGUSER
            - PGDATABASE
            - PGPASSWORD
    webapp_worker:
        image: csh_webapp
        container_name: webapp_worker
        command: python manage.py runworker
        volumes:
            - '.:/csh'
        depends_on:
            - redis
            - webapp
        environment:
            # Flask
            - SECRET_KEY
            - DEBUG
            - SECURITY_PASSWORD_SALT
            # S3 Configuration
            - RAW_UPLOADS_PATH=s3://dsapp-criminal-justice/csh/matcher/{jurisdiction}/{event_type}/uploaded/{date}/{upload_id}
            - MERGED_UPLOADS_PATH=s3://dsapp-criminal-justice/csh/matcher/{jurisdiction}/{event_type}/merged
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            # Database connection
            - PGHOST=csh_db
            - PGPORT=5432
            - PGUSER
            - PGDATABASE
            - PGPASSWORD
            # Matcher connection
            - MATCHER_LOCATION=matcher
            - MATCHER_PORT=5000
    redis:
       image: redis
       ports:
         - 6379:6379
    nginx:
        image: "nginx:1.13.5"
        ports:
            - 80:80
        volumes:
            - ./webapp/conf.d:/etc/nginx/conf.d
        depends_on: 
            - webapp
