"""empty message

Revision ID: 2873a0256a0b
Revises: 81669d0c758f
Create Date: 2018-05-11 21:40:50.984615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2873a0256a0b'
down_revision = '81669d0c758f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('match_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_log', 'match_status')
    # ### end Alembic commands ###
