"""empty message

Revision ID: 81669d0c758f
Revises: 66263cd9943c
Create Date: 2018-05-11 21:29:51.885632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81669d0c758f'
down_revision = '66263cd9943c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_log', sa.Column('upload_complete_time', sa.DateTime(), nullable=True))
    op.add_column('upload_log', sa.Column('upload_start_time', sa.DateTime(), nullable=True))
    op.add_column('upload_log', sa.Column('upload_status', sa.Boolean(), nullable=True))
    op.add_column('upload_log', sa.Column('validate_complete_time', sa.DateTime(), nullable=True))
    op.add_column('upload_log', sa.Column('validate_start_time', sa.DateTime(), nullable=True))
    op.add_column('upload_log', sa.Column('validate_status', sa.Boolean(), nullable=True))
    op.drop_column('upload_log', 'upload_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_log', sa.Column('upload_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('upload_log', 'validate_status')
    op.drop_column('upload_log', 'validate_start_time')
    op.drop_column('upload_log', 'validate_complete_time')
    op.drop_column('upload_log', 'upload_status')
    op.drop_column('upload_log', 'upload_start_time')
    op.drop_column('upload_log', 'upload_complete_time')
    # ### end Alembic commands ###
