"""empty message

Revision ID: f03a65452ad3
Revises: c13a3d1d2b85
Create Date: 2017-10-27 12:02:33.579750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03a65452ad3'
down_revision = 'c13a3d1d2b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_log', sa.Column('s3_upload_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_log', 's3_upload_path')
    # ### end Alembic commands ###
